[package]
name = "lab1_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lab1 = { path = "../lab1" }
common = { path = "../common" }

[[bin]]
name = "lab1"
path = "src/main.rs"
